apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"control-plane":"controller-manager"},"name":"ankyra-operator-controller-manager-metrics-service","namespace":"default"},"spec":{"ports":[{"name":"https","port":8443,"protocol":"TCP","targetPort":"https"}],"selector":{"control-plane":"controller-manager"}}}
  creationTimestamp: "2021-10-03T13:38:46Z"
  labels:
    control-plane: controller-manager
  name: ankyra-operator-controller-manager-metrics-service
  namespace: default
  resourceVersion: "220720"
  uid: 5e61aded-3de8-4d34-918b-a73b39735e97
spec:
  clusterIP: 10.43.237.83
  clusterIPs:
  - 10.43.237.83
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
